# Избранное
## Получить список избранных объявлений
GET http://localhost:5001/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3MxMDAwQGh0bWxhY2FkZW15LnJ1IiwibmFtZSI6Iktla3MxIiwiaWQiOiI2OTM1NjE2NmNhNWJmNWE1OTUyMDgzMmUiLCJpYXQiOjE3NjUxMTI2NDMsImV4cCI6MTc2NTI4NTQ0M30.wizEJXlu3ODKedr1-7vvnctk5x6X2Rhpt_WEFJ78UMs

###

## Добавить объявление в избранное
POST http://localhost:5001/favorites/693583ad306105af7e87931b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3MxMDAwQGh0bWxhY2FkZW15LnJ1IiwibmFtZSI6Iktla3MxIiwiaWQiOiI2OTM1NjE2NmNhNWJmNWE1OTUyMDgzMmUiLCJpYXQiOjE3NjUyMDgwNDAsImV4cCI6MTc2NTM4MDg0MH0.PQHQ6Y-dFGlkYgS3bmw4EdqvrFEsYZkvapFSk2HNvtM

###

## Удалить объявление из избранного
DELETE http://localhost:5001/favorites/693583ad306105af7e87931b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3MxMDAwQGh0bWxhY2FkZW15LnJ1IiwibmFtZSI6Iktla3MxIiwiaWQiOiI2OTM1NjE2NmNhNWJmNWE1OTUyMDgzMmUiLCJpYXQiOjE3NjUyMDg1NzgsImV4cCI6MTc2NTM4MTM3OH0.6ywgK12ZA38FkOTTTCqsRBcv36WQZOTEGycVlZK8Dis

###
